### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by bradygaster** [bradygaster/Aspiregregator#2]
question for @IEvangelist - "Aspiregregator" (i'm giving some love to my old-school favorite RSS reader, Newsgator, which appeared before Google Reader, which was everyone's favorite RSS reader prior to the team killing the product and almost killing RSS adoption in the process) or "Aspire Reader?"

**Comment by IEvangelist** [comment]
I'm good with the name, it's something that stands out and tips its imaginary hat to an old fav. Besides naming things is hard! 😄
